# Generated by Django 5.2.17 on 2026-08-26 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('core', '0002_seed_defaults'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_on', models.DateField(verbose_name='ថ្ងៃបង់')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('KHR', 'KHR')], max_length=3, verbose_name='រូបិយប័ណ្ណ')),
                ('tuition_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ថ្លៃសិក្សា')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ថ្លៃចុះឈ្មោះ')),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ថ្លៃយឺត')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='បញ្ចុះតម្លៃ')),
                ('scholarship_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='អាហារូបករ')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='សរុប')),
                ('transaction_reference', models.CharField(blank=True, max_length=80, verbose_name='លេខយោងប្រតិបត្តិការ')),
                ('period_type', models.CharField(choices=[('monthly', 'ប្រចាំខែ'), ('full_course', 'គិតតាមវគ្គ'), ('one_time', 'មួយលើក')], max_length=20, verbose_name='ប្រភេទថ្លៃ')),
                ('period_label', models.CharField(blank=True, max_length=80, verbose_name='រយៈពេល')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='ចាប់ផ្ដើមរយៈពេល')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='បញ្ចប់រយៈពេល')),
                ('previous_due_date', models.DateField(blank=True, null=True, verbose_name='Due Date មុនបង់')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Due Date បន្ទាប់')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='កំណត់ចំណាំ')),
                ('status', models.CharField(choices=[('completed', 'បានបង់'), ('voided', 'បានលុបចោល')], default='completed', max_length=20, verbose_name='ស្ថានភាព')),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255, verbose_name='មូលហេតុលុបចោល')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='academics.courseclass', verbose_name='ថ្នាក់រៀន')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='ទទួលដោយ')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='academics.enrollment', verbose_name='ការចុះឈ្មោះ')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.paymentmethod', verbose_name='វិធីបង់ប្រាក់')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='students.student', verbose_name='សិស្ស')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ការបង់ប្រាក់',
                'verbose_name_plural': 'ការបង់ប្រាក់',
                'ordering': ['-paid_on', '-created_at'],
                'permissions': [('collect_payment', 'Can collect payments'), ('void_payment', 'Can void payments')],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=24, unique=True, verbose_name='លេខបង្កាន់ដៃ')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='ថ្ងៃចេញ')),
                ('status', models.CharField(choices=[('issued', 'បានចេញ'), ('voided', 'បានលុបចោល')], default='issued', max_length=20, verbose_name='ស្ថានភាព')),
                ('school_name', models.CharField(max_length=200, verbose_name='ឈ្មោះសាលា')),
                ('school_address', models.CharField(blank=True, max_length=255, verbose_name='អាសយដ្ឋានសាលា')),
                ('school_phone', models.CharField(blank=True, max_length=50, verbose_name='ទូរសព្ទសាលា')),
                ('student_id_snapshot', models.CharField(max_length=20, verbose_name='លេខសម្គាល់សិស្ស')),
                ('student_name_kh', models.CharField(max_length=150, verbose_name='ឈ្មោះសិស្ស')),
                ('student_name_en', models.CharField(blank=True, max_length=150, verbose_name='ឈ្មោះអង់គ្លេស')),
                ('course_name', models.CharField(max_length=150, verbose_name='វគ្គសិក្សា')),
                ('class_name', models.CharField(max_length=150, verbose_name='ថ្នាក់រៀន')),
                ('issued_by_name', models.CharField(blank=True, max_length=150, verbose_name='ឈ្មោះអ្នកចេញ')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_receipts', to=settings.AUTH_USER_MODEL, verbose_name='ចេញដោយ')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='billing.payment', verbose_name='ការបង់ប្រាក់')),
            ],
            options={
                'verbose_name': 'បង្កាន់ដៃ',
                'verbose_name_plural': 'បង្កាន់ដៃ',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-paid_on', '-created_at'], name='billing_pay_paid_on_4b738c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='billing_pay_status_b7739e_idx'),
        ),
    ]
