# Generated by Django 5.2.17 on 2026-08-26 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0003_schoolsettings_telegram_admin_chat_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_on', '-created_at'], 'permissions': [('collect_payment', 'Can collect payments'), ('void_payment', 'Can void payments'), ('refund_payment', 'Can refund payments')], 'verbose_name': 'ការបង់ប្រាក់', 'verbose_name_plural': 'ការបង់ប្រាក់'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('completed', 'បានបង់'), ('voided', 'បានលុបចោល'), ('refunded', 'បានសងប្រាក់')], default='completed', max_length=20, verbose_name='ស្ថានភាព'),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refunded_on', models.DateField(verbose_name='ថ្ងៃសង')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ចំនួនសង')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('KHR', 'KHR')], max_length=3, verbose_name='រូបិយប័ណ្ណ')),
                ('reason', models.CharField(max_length=255, verbose_name='មូលហេតុ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_refunds', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='core.paymentmethod', verbose_name='វិធីសងប្រាក់')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='billing.payment', verbose_name='ការបង់ប្រាក់')),
            ],
            options={
                'verbose_name': 'ការសងប្រាក់',
                'verbose_name_plural': 'ការសងប្រាក់',
                'ordering': ['-refunded_on', '-created_at'],
            },
        ),
    ]
