# Generated by Django 5.2.17 on 2026-08-26 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ឈ្មោះវគ្គ')),
                ('name_kh', models.CharField(blank=True, max_length=150, verbose_name='ឈ្មោះជាភាសាខ្មែរ')),
                ('description', models.TextField(blank=True, verbose_name='ពិពណ៌នា')),
                ('fee_type', models.CharField(choices=[('monthly', 'ប្រចាំខែ'), ('full_course', 'គិតតាមវគ្គ'), ('one_time', 'មួយលើក')], max_length=20, verbose_name='ប្រភេទថ្លៃ')),
                ('default_fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ថ្លៃសិក្សា')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('KHR', 'KHR')], default='USD', max_length=3, verbose_name='រូបិយប័ណ្ណ')),
                ('is_active', models.BooleanField(default=True, verbose_name='កំពុងប្រើ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'វគ្គសិក្សា',
                'verbose_name_plural': 'វគ្គសិក្សា',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ឈ្មោះថ្នាក់')),
                ('instructor_name', models.CharField(blank=True, max_length=150, verbose_name='គ្រូបង្រៀន')),
                ('start_date', models.DateField(verbose_name='ថ្ងៃចាប់ផ្ដើម')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='ថ្ងៃបញ្ចប់')),
                ('study_days', models.JSONField(default=list, verbose_name='ថ្ងៃសិក្សា')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='ម៉ោងចាប់ផ្ដើម')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='ម៉ោងបញ្ចប់')),
                ('is_active', models.BooleanField(default=True, verbose_name='កំពុងប្រើ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academics.course', verbose_name='វគ្គសិក្សា')),
            ],
            options={
                'verbose_name': 'ថ្នាក់រៀន',
                'verbose_name_plural': 'ថ្នាក់រៀន',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'កំពុងរៀន'), ('suspended', 'ផ្អាក'), ('dropped', 'បោះបង់'), ('transferred', 'ផ្ទេរ'), ('completed', 'បញ្ចប់')], default='active', max_length=20, verbose_name='ស្ថានភាព')),
                ('enrolled_on', models.DateField(verbose_name='ថ្ងៃចុះឈ្មោះ')),
                ('ended_on', models.DateField(blank=True, null=True, verbose_name='ថ្ងៃបញ្ចប់')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Due Date បន្ទាប់')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='កំណត់ចំណាំ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.courseclass', verbose_name='ថ្នាក់រៀន')),
            ],
            options={
                'verbose_name': 'ការចុះឈ្មោះ',
                'verbose_name_plural': 'ការចុះឈ្មោះ',
                'ordering': ['-enrolled_on', '-created_at'],
                'permissions': [('change_enrollment_status', 'Can change enrollment status')],
            },
        ),
    ]
