# Generated by Django 5.2.17 on 2026-08-27 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_courseclass_instructor'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_on', models.DateField(verbose_name='ថ្ងៃ')),
                ('status', models.CharField(choices=[('present', 'មានវត្តមាន'), ('absent', 'អវត្តមាន'), ('excused', 'ច្បាប់')], max_length=20, verbose_name='ស្ថានភាព')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='កំណត់ចំណាំ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='academics.courseclass', verbose_name='ថ្នាក់រៀន')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='academics.enrollment', verbose_name='ការចុះឈ្មោះ')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL, verbose_name='ចុះដោយ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='students.student', verbose_name='សិស្ស')),
            ],
            options={
                'verbose_name': 'វត្តមាន',
                'verbose_name_plural': 'វត្តមាន',
                'ordering': ['-attended_on', 'student__name_kh'],
                'permissions': [('mark_attendance', 'Can mark attendance')],
                'indexes': [models.Index(fields=['attended_on'], name='academics_a_attende_63e812_idx'), models.Index(fields=['course_class', 'attended_on'], name='academics_a_course__3cdd8e_idx')],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'attended_on'), name='unique_attendance_per_enrollment_day')],
            },
        ),
    ]
