# Generated by Django 5.2.17 on 2026-08-28 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_attendancerecord'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ឈ្មោះប្រឡង')),
                ('assessed_on', models.DateField(verbose_name='ថ្ងៃប្រឡង')),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=6, verbose_name='ពិន្ទុពេញ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.courseclass', verbose_name='ថ្នាក់រៀន')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ប្រឡង',
                'verbose_name_plural': 'ប្រឡង',
                'ordering': ['-assessed_on', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='ពិន្ទុ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='academics.assessment', verbose_name='ប្រឡង')),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_records', to='academics.courseclass', verbose_name='ថ្នាក់រៀន')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_records', to='academics.enrollment', verbose_name='ការចុះឈ្មោះ')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_scores', to=settings.AUTH_USER_MODEL, verbose_name='ដាក់ដោយ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_records', to='students.student', verbose_name='សិស្ស')),
            ],
            options={
                'verbose_name': 'ពិន្ទុ',
                'verbose_name_plural': 'ពិន្ទុ',
                'ordering': ['student__name_kh'],
                'permissions': [('mark_score', 'Can mark scores')],
            },
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('course_class', 'name', 'assessed_on'), name='unique_assessment_per_class_name_day'),
        ),
        migrations.AddConstraint(
            model_name='scorerecord',
            constraint=models.UniqueConstraint(fields=('assessment', 'enrollment'), name='unique_score_per_enrollment_assessment'),
        ),
    ]
