# Generated by Django 5.2.17 on 2026-08-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_assessment_and_scorerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'វត្តមាន'), ('late', 'យឺត'), ('excused', 'សុំច្បាប់'), ('absent', 'អវត្តមាន')], max_length=20, verbose_name='ស្ថានភាព'),
        ),
    ]
