# Generated by Django 5.2.17 on 2026-08-26 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='លេខសម្គាល់សិស្ស')),
                ('photo', models.ImageField(blank=True, upload_to='students/%Y/%m/', verbose_name='រូបថត')),
                ('name_kh', models.CharField(max_length=150, verbose_name='ឈ្មោះជាភាសាខ្មែរ')),
                ('name_en', models.CharField(max_length=150, verbose_name='ឈ្មោះជាភាសាអង់គ្លេស')),
                ('gender', models.CharField(choices=[('male', 'ប្រុស'), ('female', 'ស្រី')], max_length=10, verbose_name='ភេទ')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='ថ្ងៃខែឆ្នាំកំណើត')),
                ('phone', models.CharField(max_length=30, verbose_name='លេខទូរសព្ទ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='អ៊ីមែល')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='អាសយដ្ឋាន')),
                ('guardian_name', models.CharField(blank=True, max_length=150, verbose_name='ឈ្មោះអាណាព្យាបាល')),
                ('guardian_phone', models.CharField(blank=True, max_length=30, verbose_name='ទូរសព្ទអាណាព្យាបាល')),
                ('guardian_relationship', models.CharField(blank=True, max_length=80, verbose_name='តំណាង')),
                ('notes', models.TextField(blank=True, verbose_name='កំណត់ចំណាំ')),
                ('is_active', models.BooleanField(default=True, verbose_name='កំពុងប្រើ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to=settings.AUTH_USER_MODEL, verbose_name='បង្កើតដោយ')),
            ],
            options={
                'verbose_name': 'សិស្ស',
                'verbose_name_plural': 'សិស្ស',
                'ordering': ['-created_at'],
                'permissions': [('enroll_student', 'Can enroll students in classes')],
            },
        ),
    ]
