# Generated by Django 5.2.17 on 2026-08-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='ឈ្មោះ')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='កូដ')),
                ('requires_reference', models.BooleanField(default=True, verbose_name='ត្រូវការ Transaction Reference')),
                ('is_active', models.BooleanField(default=True, verbose_name='កំពុងប្រើ')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='លំដាប់')),
            ],
            options={
                'verbose_name': 'វិធីបង់ប្រាក់',
                'verbose_name_plural': 'វិធីបង់ប្រាក់',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200, verbose_name='ឈ្មោះសាលា')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='អាសយដ្ឋាន')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='លេខទូរសព្ទ')),
                ('logo', models.ImageField(blank=True, upload_to='school/', verbose_name='និមិត្តសញ្ញា')),
                ('reminder_days_before_due', models.PositiveSmallIntegerField(default=3, verbose_name='ជូនដំណឹងមុន Due Date (ថ្ងៃ)')),
                ('overdue_alert_daily', models.BooleanField(default=True, verbose_name='ជូនដំណឹង overdue រាល់ថ្ងៃ')),
            ],
            options={
                'verbose_name': 'ការកំណត់សាលា',
                'verbose_name_plural': 'ការកំណត់សាលា',
            },
        ),
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('key', 'year'), name='unique_number_sequence_per_year')],
            },
        ),
    ]
