# Generated by Django 5.2.17 on 2026-08-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='telegram_admin_chat_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='Telegram Admin Chat ID'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=120, verbose_name='Telegram Bot Token'),
        ),
    ]
