# Generated by Django 5.2.17 on 2026-08-26 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ពេលវេលា')),
                ('actor_name', models.CharField(blank=True, max_length=150, verbose_name='ឈ្មោះអ្នកប្រើ')),
                ('action', models.CharField(choices=[('payment.collected', 'ទទួលបង់ប្រាក់'), ('payment.voided', 'លុបចោលការបង់'), ('payment.refunded', 'សងប្រាក់'), ('student.created', 'បង្កើតសិស្ស'), ('student.updated', 'កែសិស្ស'), ('student.deleted', 'លុបសិស្ស'), ('enrollment.created', 'ចុះឈ្មោះ'), ('enrollment.transferred', 'ផ្ទេរថ្នាក់'), ('enrollment.status', 'ប្ដូរស្ថានភាព'), ('settings.updated', 'កែការកំណត់'), ('telegram.sent', 'ផ្ញើ Telegram'), ('telegram.failed', 'Telegram បរាជ័យ')], max_length=40, verbose_name='សកម្មភាព')),
                ('object_type', models.CharField(blank=True, max_length=40, verbose_name='ប្រភេទ')),
                ('object_id', models.CharField(blank=True, max_length=40, verbose_name='លេខសម្គាល់')),
                ('object_label', models.CharField(blank=True, max_length=255, verbose_name='វត្ថុ')),
                ('summary', models.CharField(max_length=255, verbose_name='សេចក្ដីសង្ខេប')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='ព័ត៌មានបន្ថែម')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកប្រើ')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_audit_created_e208ff_idx'), models.Index(fields=['action'], name='audit_audit_action_203f66_idx')],
            },
        ),
    ]
