# Generated by Django 5.2.17 on 2026-08-26 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('due_soon', 'ជិតដល់ Due Date'), ('overdue', 'ហួស Due Date'), ('test', 'សារសាកល្បង')], max_length=20, verbose_name='ប្រភេទ')),
                ('channel', models.CharField(default='telegram', max_length=20, verbose_name='ឆានែល')),
                ('sent_on', models.DateField(verbose_name='ថ្ងៃផ្ញើ')),
                ('status', models.CharField(choices=[('sent', 'បានផ្ញើ'), ('failed', 'បរាជ័យ'), ('skipped', 'រំលង')], max_length=20, verbose_name='ស្ថានភាព')),
                ('message', models.TextField(blank=True, verbose_name='សារ')),
                ('error', models.CharField(blank=True, max_length=255, verbose_name='កំហុស')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_logs', to='academics.enrollment', verbose_name='ការចុះឈ្មោះ')),
            ],
            options={
                'verbose_name': 'ការជូនដំណឹង',
                'verbose_name_plural': 'ការជូនដំណឹង',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('enrollment__isnull', False)), fields=('enrollment', 'kind', 'sent_on'), name='unique_enrollment_notice_per_day')],
            },
        ),
    ]
